- name: add gnome repo 1
  apt_repository: repo='ppa:gnome3-team/gnome3-staging' state=present
- name: add gnome repo 2
  apt_repository: repo='ppa:gnome3-team/gnome3' state=present
- name: add atom repo
  apt_repository: repo='ppa:webupd8team/atom' state=present

- name: updating APT cache
  apt: update_cache=yes

- name: install curl
  apt: name=curl state=latest

- name: install mc
  apt: name=mc state=latest

- name: Install nload
  apt: name=nload state=latest

- name: install git
  apt: name=git state=latest

- name: install htop
  apt: name=htop state=latest

- name: install zsh
  apt: name=zsh state=latest

- name: install chromium-browser
  apt: name=chromium-browser state=latest

- name: install openjdk-8-jdk
  apt: name=openjdk-8-jdk state=latest

- name: install atom
  apt: name=atom state=latest

- name: install keepass2
  apt: name=keepass2 state=latest

- name: install GUAKE
  apt: name=guake state=latest
  notify:
    - set startup GUAKE

- name: install MONACO font
  shell: curl -kL https://raw.github.com/cstrap/monaco-font/master/install-font-ubuntu.sh | bash
  run_once: true

- name: downalod ohmyzsh
  shell: curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
  run_once: true

- name: add RVM server key
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: instal RVM
  shell: curl -L https://get.rvm.io | bash -s stable

- name: add RVM to autostart
  shell: /bin/bash -l -c "echo -e \"\nsource /usr/local/rvm/scripts/rvm\" >> ~/.bashrc"

- name: add RVM to autostart
  shell: /bin/bash -l -c "source /usr/local/rvm/scripts/rvm"

# - include: docker/install.yml
